Exporter APS Authentication
Autodesk/synthesis pull request #1001
Opened 2024-06-27 22:44 UTC by PepperLola

Changes:
- Palette to get authorization code for Autodesk account
- Fetches code and refreshes automatically once expired
- Shows first name in a new tab in the main exporter panel (temporary)

> [!WARNING]
> I haven't yet tested refreshing the token once it's expired. The web request works though and gets a different access token than before.

2024-06-28 17:06 UTC, BrandonPacewic requested changes
I get the following error upon attempt to open the API panel.

<img width="495" alt="image" src="https://github.com/Autodesk/synthesis/assets/92102436/e6dba057-78f2-47f0-89c8-cb7330e1f260">

2024-07-02 17:51 UTC, BrandonPacewic approved these changes
Seems to work...

The security workflow is getting real mad at us with this one, not sure if there is anything we can do to fix that though.

2024-07-03 05:49 UTC, HunterBarclay commented
@PepperLola Something to note: I forgot to switch the server branch over so I ran into an issue. That being said, after getting the issue, there isn't any way for me to reset the aps login process without restarting the addin. Could we have to detect an error and then automatically reset?

2024-07-03 05:51 UTC, HunterBarclay commented
@PepperLola I get this page in the palette, and then nothing further:

<img width="731" alt="image" src="https://github.com/Autodesk/synthesis/assets/20159878/f8ff7fd3-5eb9-4f0f-b9ee-056d6ef6d7d7">

2024-07-03 05:52 UTC, HunterBarclay commented
It does appear to successfully login, however.

<img width="725" alt="image" src="https://github.com/Autodesk/synthesis/assets/20159878/b4d1ebdb-4961-4ccb-83d1-9d330cdd0f99">

2024-07-06 19:10 UTC, Ewie21 approved these changes
I know I'm super late to the party, but everything worked for me.

2024-07-06 19:10 UTC, Ewie21 commented on exporter/SynthesisFusionAddin/src/APS/APS.py
> +    authUrl = f'http://localhost:3003/api/aps/code/?code={code}&redirect_uri={urllib.parse.quote_plus("http://localhost:3003/api/aps/exporter/")}'
These will have to be changed to the actually URL eventually, right? A constant might be helpful for this.

2024-07-09 18:42 UTC, merged