APS File Upload
Autodesk/synthesis pull request #1004
Opened 2024-06-28 19:29 UTC by Ewie21

### Description
Functions to interface with APS data management, the main purpose is to upload mirabuf files to a users's hub, so they can be easily accessed by fission.
Every user has a hub, in their hub they have a project, in which there are folders, in which there are buckets. Files are inside buckets.

### Objectives
- [x] Getters for hub ids, project ids, folder ids, file ids
- [x] Upload files to specific folder
- [x] Interface with the APS versioning system to upload new versions of mirabuf files

### Testing Done
- [ ] Test with janky Hunter's solution
- [ ] Test with #1001

Blocked by #1001

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1721)

2024-07-17 16:32 UTC, HunterBarclay approved these changes
Works great. Slowly discovering more issues with the Simulator, now that we can bring in more bots.

2024-07-17 16:41 UTC, HunterBarclay commented
@Ewie21 Make sure you format

2024-07-17 16:54 UTC, BrandonPacewic requested changes
~~There are some changes in `ConfigCommand.py` that seem to be friction exporting changes. Did some of the friction re-implementation get accidently pushed to this branch?~~

2024-07-17 17:18 UTC, Ewie21 commented
> There are some changes in `ConfigCommand.py` that seem to be friction exporting changes. Did some of the friction re-implementation get accidently pushed to this branch?

I removed a block of code that had already been commented out. The boolean changes were probably me testing to see what properties did. They shouldn't matter at all because all of that will get overriden by #1004.

2024-07-17 23:39 UTC, BrandonPacewic commented on exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
> +                    savepath = FileDialogConfig.SaveFileDialog(defaultPath=exporterOptions.fileLocation)
- Note to my future self, there will be a conflict with #995.

2024-07-17 23:49 UTC, BrandonPacewic requested changes

2024-07-17 23:49 UTC, BrandonPacewic commented on exporter/SynthesisFusionAddin/src/UI/ConfigCommand.py
> +                savepath = processedFileName
This `if` statement should be using the current selected export location not the one currently saved to the design. Which is what the `exporterOptions` object is here.

2024-07-18 17:46 UTC, BrandonPacewic approved these changes
Still some problems with exporting a robot without APS and the docker container running. I believe that most of these problems were introduced in a different PR so no need to try and fix them here.

This is certainly good enough to get things started!

2024-07-19 06:11 UTC, merged