Transform Gizmos on Mirabuf Assemblies
Autodesk/synthesis pull request #1009
Opened 2024-07-02 00:57 UTC by Dhruv-0-Arora

### Description
This branch adds transform gizmos to the mirabuf assemblies as they spawn in. These transform gizmos currently are always on the Mirabuf assemblies as they spawn. The physics system is disabled when the user presses the transform gizmo (will implement so physics is disabled for only the one assembly and also it stays disable as long as the gizmo is attached).

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1733)

2024-07-02 06:40 UTC, Dhruv-0-Arora commented
Rn it does not set Rotation or Scale. Only position

2024-07-03 09:56 UTC, Dhruv-0-Arora commented
Completely ready for review

2024-07-03 17:32 UTC, HunterBarclay requested changes
I added a quick change to your PR that also sets the bodies to be sensors when disabled, meaning they won't act on generated collision contacts.

When spawning in a field, we should restrict it to translation movement only. Not rotation. I also noticed that after finishing with the gizmo, if I try to move the camera by clicking near the center of the screen, it doesn't work, I have to click on the edge, and then it essentially snaps out of it and I can orbit the camera like normal.

2024-07-03 18:29 UTC, HunterBarclay requested changes
Nearly there, just a few tweaks. After positioning everything, the robot doesn't interact with the gampieces and the arm of mean machine doesn't interact with anything. Fix is added.

2024-07-03 18:29 UTC, HunterBarclay commented on fission/src/mirabuf/MirabufSceneObject.ts
> +                World.PhysicsSystem.DisablePhysicsForBody(this._mechanism.GetBodyByNodeId(rn.id)!)
Having this run every frame probably isn't the best idea.

2024-07-03 18:29 UTC, HunterBarclay commented on fission/src/mirabuf/MirabufSceneObject.ts
> +                    World.PhysicsSystem.EnablePhysicsForBody(this._mechanism.GetBodyByNodeId(this._mechanism.rootBody)!)
```suggestion
                    World.PhysicsSystem.EnablePhysicsForBody(this._mechanism.GetBodyByNodeId(rn.id)!)
```

2024-07-03 18:42 UTC, Dhruv-0-Arora commented on fission/src/mirabuf/MirabufSceneObject.ts
> +                World.PhysicsSystem.DisablePhysicsForBody(this._mechanism.GetBodyByNodeId(rn.id)!)
Oh what I forgot to change that

2024-07-08 17:27 UTC, HunterBarclay requested changes

2024-07-08 17:27 UTC, HunterBarclay commented on fission/src/mirabuf/MirabufSceneObject.ts
> +            }
You should move this to only be done once per update, not for each node. You're running into an issue where enter and escape are only being detected in one of these loops before being discarded so running enable on all the rigid nodes doesn't work.

2024-07-08 17:27 UTC, HunterBarclay commented on fission/src/mirabuf/MirabufSceneObject.ts
> +        this._mirabufInstance.parser.rigidNodes.forEach(rn => {
Please turn adding and removing the gizmos and essentially "putting the mirabuf object in move mode" into a separate function for reusability

2024-07-09 23:59 UTC, PepperLola reviewed
Are the negative axis arrows supposed to be partially invisible? Also, I noticed the squares for moving along a plane disappear when the angle between them and the camera is too shallow. Not sure if there's much you can do about that though but I could be wrong.

2024-07-10 05:38 UTC, Dhruv-0-Arora commented
> Are the negative axis arrows supposed to be partially invisible? Also, I noticed the squares for moving along a plane disappear when the angle between them and the camera is too shallow. Not sure if there's much you can do about that though but I could be wrong.

Well I can't really do much about either since it is the built in transform gizmo from three.js. the negative axis arrows being partially invisible is intentional on their end

2024-07-10 21:07 UTC, HunterBarclay approved these changes
I'm approving this for now because we want it in for the MVP and it's currently blocking two critical tasks. That being said I created a new Jira ticket for Sprint 4 to address a lot of the issues I have with Transform Gizmos.

2024-07-10 21:07 UTC, HunterBarclay commented on fission/src/Window.d.ts
This file was removed in dev, what's going on with this file?

2024-07-10 21:07 UTC, HunterBarclay commented on fission/src/mirabuf/MirabufSceneObject.ts
> +    private _deleteGizmoOnEscape: boolean = true
I'll let this be for now, but the entirety of transform gizmos needs a major refactor to be more adaptable. It should honestly be worked into some kind of UI component. [Jira ticket for refactoring](https://jira.autodesk.com/browse/AARD-1744)

2024-07-10 21:07 UTC, HunterBarclay commented on fission/src/Window.d.ts
@PepperLola You know what's up with this file?

2024-07-10 21:07 UTC, HunterBarclay commented on fission/src/ui/components/TransformGizmos.tsx
This isn't a UI component as it stands atm.

2024-07-10 21:22 UTC, BrandonPacewic approved these changes
Let's get this MVP done!

2024-07-10 21:57 UTC, merged