Colbura/1709/aps logout
Autodesk/synthesis pull request #1016
Opened 2024-07-08 21:51 UTC by Ewie21

### Description
Allows logout from your APS account in the fusion exporter.

### TODO:
- [x] Write functions to logout
- [ ] Create UI button that calls function(s)

### Testing Done
- [ ] Test logout

Testing and UI blocked by #1001

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1709)

2024-07-10 21:17 UTC, HunterBarclay commented
So, quick note. This ticket was actually meant for Fission, not Fusion. Regardless, both should be done so could you extend this PR into also adding proper revoking capabilities to Fission as well?

2024-07-12 23:21 UTC, BrandonPacewic reviewed
@Ewie21 Ready for review? Looks like there are still some `TODO`s unchecked.

2024-07-15 17:20 UTC, BrandonPacewic requested changes
Looks good! One minor request is that we stick to camel case for function names.

2024-07-15 17:20 UTC, BrandonPacewic commented on fission/src/aps/APS.ts
> +        if (!(await this.revoke_token_public())) return
```suggestion
        if (!(await this.revokeTokenPublic())) return
```

2024-07-15 17:20 UTC, BrandonPacewic commented on fission/src/aps/APS.ts
> +    static async revoke_token_public(): Promise<boolean> {
```suggestion
    static async revokeTokenPublic(): Promise<boolean> {
```

2024-07-17 16:47 UTC, HunterBarclay requested changes
Revoked great, couple changes.

2024-07-17 16:47 UTC, HunterBarclay commented on fission/bun.lockb
Can we remove this. I believe it is in the git ignore in dev.

2024-07-17 16:47 UTC, HunterBarclay commented on fission/src/aps/APS.ts
> +        if (!(await this.revoke_token_public())) return
If the token isn't revoked, lets just drop it anyways.

2024-07-17 23:52 UTC, BrandonPacewic commented on fission/src/aps/APS.ts
> +     * Does nothing if the auth token couldn't be revoked
Should this comment line be removed now that we always set the auth token to undefined even if we can't revoke the token?

```suggestion
```

2024-07-18 17:48 UTC, BrandonPacewic approved these changes
Revoking my stale review...

2024-07-24 22:09 UTC, PepperLola approved these changes
Looks like it works well. For some reason I'm still able to get my own user info after revoking the token but nothing else works (which is good).

2024-07-26 17:22 UTC, HunterBarclay approved these changes

2024-07-26 17:22 UTC, merged