Delete Assembly Hot Fix
Autodesk/synthesis pull request #1027
Opened 2024-07-15 20:06 UTC by Dhruv-0-Arora

### Description
- [x] Fixed Bug: deleting assemblies from ManageAssembliesModal does not delete the transform gizmo attached
- [x] Removed duplicate GetRootNodeId() implementation in MirabufSceneObject.ts
- [x] Removed inaccessible variable _deleteGizmoOnEscape

2024-07-15 22:57 UTC, HunterBarclay requested changes

2024-07-15 22:57 UTC, HunterBarclay commented on fission/src/ui/modals/spawning/ManageAssembliesModal.tsx
> +                    (World.SceneRenderer.sceneObjects.get(id) as MirabufSceneObject).DisableTransformControls()
I would move this to be included in the Dispose function of `MirabufSceneObject`

2024-07-15 22:57 UTC, HunterBarclay commented on fission/src/mirabuf/MirabufSceneObject.ts
>      public EnableTransformControls(): void {
What happens if this is called when the transform gizmo is already enabled? Will it handle it accordingly?

2024-07-16 02:29 UTC, a-crowell reviewed
Hotfix looks good! Once `EnableTransformControls` handles already being enabled, LGTM.

2024-07-16 03:30 UTC, a-crowell approved these changes
Lovely

2024-07-16 16:28 UTC, HunterBarclay approved these changes

2024-07-16 16:28 UTC, HunterBarclay commented
@Dhruv-0-Arora Please fix merge conflicts

2024-07-16 17:14 UTC, Dhruv-0-Arora commented
> @Dhruv-0-Arora Please fix merge conflicts

Fixed them 👍

2024-07-16 17:24 UTC, merged