UI Touchups
Autodesk/synthesis pull request #1038
Opened 2024-07-20 21:46 UTC by HunterBarclay

### Description
Getting the UI ready for users. Little things here and there I don't mind, but I want to get general issues that inhibit the usage of the application out of the way.

### Tasks
- [x] Fixed overflow on import panel
- [x] Removed most buttons from MainHUD
- [x] Moved debugging and testing related buttons to a new debug panel

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1739)

2024-07-22 18:42 UTC, Dhruv-0-Arora requested changes

2024-07-22 18:42 UTC, Dhruv-0-Arora commented on fission/src/ui/panels/DebugPanel.tsx
> +            name={"The Poker"}
```suggestion
            name={"Debug Panel"}
```

2024-07-22 19:41 UTC, LucaHaverty commented
Do we need multibot on the main hud anymore?

2024-07-25 09:25 UTC, Dhruv-0-Arora requested changes
Could you resolve merge conflicts rq 😄

2024-07-25 16:51 UTC, LucaHaverty approved these changes
Looks great! Just a quick merge and It'll be great.

2024-07-25 17:45 UTC, Dhruv-0-Arora approved these changes
Looks good 👍

2024-07-25 17:57 UTC, merged