Toolbar Buttons
Autodesk/synthesis pull request #1053
Opened 2024-07-26 19:40 UTC by azaleacolburn

### Description
Add button that links to synthesis tutorials in the exporter toolbar.

### Testing Done
- Click the button and go to the website

I thought this PR was opened already

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1688)

2024-07-26 22:53 UTC, PepperLola commented
When the addon starts, I get an error saying that 'UI.Helper' has no attribute 'check_solid_open' in `Synthesis.py:138`.

2024-07-26 22:55 UTC, BrandonPacewic commented on exporter/SynthesisFusionAddin/Synthesis.py
> +        Helper.check_solid_open,
> When the addon starts, I get an error saying that 'UI.Helper' has no attribute 'check_solid_open' in `Synthesis.py:138`.

This was a merge conflict, left this to be changed in the HUI refactor.

```suggestion
        lambda *_: True,
```

2024-07-26 23:09 UTC, BrandonPacewic reviewed
@azaleacolburn I would recommend running the format script in [`exporter/SynthesisFusionAddin/Synthesis.py`](https://github.com/Autodesk/synthesis/blob/f467f95d3e62fe23b319135c2ebdd7a68dca643d/exporter/SynthesisFusionAddin/tools/format.py) if you are not already 🙃

2024-07-26 23:27 UTC, PepperLola approved these changes
Works now

2024-07-26 23:33 UTC, BrandonPacewic requested changes
Looks like there are still some left over formatting changes, for some reason some files are formatted to have max 80 character columns when it should be 120.

Reseting those files to their state on `dev` should do the trick.

2024-07-29 23:43 UTC, BrandonPacewic approved these changes
Just reverted the formatting changes that occurred 🙃

2024-07-30 18:37 UTC, merged