Combined Configuration
Autodesk/synthesis pull request #1068
Opened 2024-07-30 22:40 UTC by LucaHaverty

### Description
Merging all of the different assembly configuration panels into one. This includes intake config, ejector config, inputs, sequential joints, and scoring zones. 

### Objectives
- [x] Panel Navigation
- [ ] Intake config support
- [ ] Ejector config support
- [ ] Input config support
- [ ] Sequential join config support
- [ ] Scoring zone config support

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1783)

2024-08-07 18:42 UTC, HunterBarclay reviewed
Actually so cool! The only thing I could find was that when adding a robot via the config panel, the config panel stayed open underneath it. Should that be closed?

2024-08-07 18:47 UTC, LucaHaverty commented
> Actually so cool! The only thing I could find was that when adding a robot via the config panel, the config panel stayed open underneath it. Should that be closed?

@HunterBarclay Yes I think so. Eventually we could modify the panel management to only allow one panel at a time open in each location to prevent them from overlapping or hiding beneath each other.

2024-08-08 21:39 UTC, Dhruv-0-Arora requested changes, later dismissed
Right now the MainHUD is looking like this
<img width="275" alt="Screenshot 2024-08-08 at 2 38 22 PM" src="https://github.com/user-attachments/assets/3b1857d6-b95c-4fd5-b853-a2ff04a86782">

With PR #1071 it will leave settings in its own little gap. Do we want to maybe combine everything or something?

2024-08-08 23:04 UTC, a-crowell requested changes
This is incredibly impressive. You meant it when you said there was a lot in the PR.

I do miss the Cancel functionality, but I can see it doesn't really work with this UI. Could "Reset" reset values back to where they were before opening the panel rather than default values? I think users will use that more. That, or a "Save" button.

Other than that, only saw a couple of minor things that could be merged in without issue. The requested changes is purely for Cancel. Great work!

Luna's Joint 5 has an odd command. Is ctrl+N an issue?
![image](https://github.com/user-attachments/assets/200f1b9f-4a2d-45cb-8a77-c6f2fe7552be)

Random lines appear if you go too fast across the selection:
![image](https://github.com/user-attachments/assets/870cfc40-7e7a-4f2e-9027-9026aca95d2e)

Is there a way to disable the arrow keys being used to scroll in the Input panel while binding keys?

Could Spawn open to Fields when opened from the Fields interface in Configuration?

2024-08-08 23:04 UTC, a-crowell commented on fission/src/ui/panels/configuring/ConfigureRobotBrainPanel.tsx
Should we test this file with a temporary button? It isn't being used yet as far as I can tell.

2024-08-08 23:04 UTC, a-crowell commented on fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
> +            name={"Configure Assemblies"}
If I remember correctly, the "Assemblies" was being removed.

2024-08-08 23:04 UTC, a-crowell commented on fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
> +    new ConfigModeSelectionOption("Joints", ConfigMode.MOTORS),
"Sequential Joints" could help specify.

Unless the velocities/accelerations are being added to this interface. That'd be fun since Subsystems in #1078 goes based on drivers including Drive, while Joints here goes based on behaviors.

2024-08-08 23:04 UTC, a-crowell commented on fission/src/ui/panels/configuring/assembly-config/ConfigurePanel.tsx
> +                        //console.log(v)
Can we delete this? There are a couple of extraneous logs.

2024-08-08 23:04 UTC, a-crowell commented on fission/src/ui/panels/configuring/assembly-config/interfaces/ConfigureShotTrajectoryInterface.tsx
> +                    setEjectorVelocity((MIN_VELOCITY + MAX_VELOCITY) / 2.0)
Could this be set to the default of 1 or the default could change to this? Intake slider reset looks good.

2024-08-08 23:11 UTC, LucaHaverty commented on fission/src/ui/panels/configuring/ConfigureRobotBrainPanel.tsx
I think the idea is to remake the brain config panel as an integrated part of the main configuration panel later, so for now we can probably just leave it unused

2024-08-08 23:16 UTC, a-crowell commented on fission/src/ui/panels/configuring/ConfigureRobotBrainPanel.tsx
Any bugs in there can be figured out when we start using it, sounds good to me.

2024-08-09 17:54 UTC, a-crowell approved these changes
Looks great! Leaving cancel/save for next pr.

2024-08-09 17:56 UTC, BrandonPacewic approved these changes
Tried and failed to break anything. This is significantly better imo.

2024-08-09 18:35 UTC, merged