Quality Configuration
Autodesk/synthesis pull request #1070
Opened 2024-07-31 19:12 UTC by Dhruv-0-Arora

### Description
Creating a separate panel for users to configure the different quality settings to either boost performance or enhance the graphics

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1780)

2024-08-07 23:15 UTC, LucaHaverty commented
Hovering over the '?' icon causes a jittering behavior for me because it shifts the panel over slightly

2024-08-21 18:01 UTC, LucaHaverty commented
Is this PR waiting for something else to be merged in or on hold?

2024-08-21 18:18 UTC, LucaHaverty reviewed
I feel like the vast majority of users won't know what things like "cascades" and "shadow map size" are, so in my opinion it would be better to have preset quality levels that we know are stable rather than give them control over all the specific settings with the potential of breaking something or ending up with crazy artifacts.

2024-08-21 18:58 UTC, BrandonPacewic commented
> I feel like the vast majority of users won't know what things like "cascades" and "shadow map size" are, so in my opinion it would be better to have preset quality levels that we know are stable rather than give them control over all the specific settings with the potential of breaking something or ending up with crazy artifacts.

I agree, but I do think we should eventually have both as an option. Similar to how most games give you low, medium, and high presets but still let you change whatever specific option you want. (At your own risk of course).

2024-08-21 18:59 UTC, BrandonPacewic reviewed
> I feel like the vast majority of users won't know what things like "cascades" and "shadow map size" are, so in my opinion it would be better to have preset quality levels that we know are stable rather than give them control over all the specific settings with the potential of breaking something or ending up with crazy artifacts.

I agree, but I do think we should eventually have both as an option. Similar to how most games give you low, medium, and high presets but still let you change whatever specific option you want. (At your own risk of course).

2025-06-18 16:26 UTC, BrandonPacewic requested changes
Additionally I don't know if I'm the biggest fan of having the panel for settings open in a different place compared to the main settings panel. It does make sense from a visual perspective so you can see what changes your actually making. Open to feedback on that.

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/src/systems/scene/SceneRenderer.ts
> +        // })
Does this update still not need to be done?

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/.eslintrc.cjs
If possible we should avoid formatting these files beyond what has already been done. We don't enforce style here so your essentially putting your own auto formatting standards onto the repo.

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/README.md
Same as above. I'm not necessarily opposed to letting these changes go through since this file was already poorly formatted.

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/postcss.config.js
Same as before. We should leave this change in though since we use double quotes and trailing commas anyways.

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/src/systems/scene/SceneRenderer.ts
> +            // logarithmicDepthBuffer: true,
This still need to be here? Should add a comment if we want it to be a reference for later.

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/src/ui/panels/GraphicsSettingsPanel.tsx
> +                    </SectionLabel>
I'm partial to the opinion that this label should be removed. At first I thought it was some sort of button or toggle and it seemed out of place.

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/src/ui/panels/GraphicsSettingsPanel.tsx
> +                />
Should probably have some sort of user confirmation here before you auto refresh and reset the current scene. Could do this by adding some sort of confirmation after the user clicks accept with a change to this option or could be saved with some sort of "Refresh is required to apply some settings" message.

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/tailwind.config.mjs
Same as other formatting changes comment. While I agree that this file is also poorly formatted this should probably be its own pr.

2025-06-18 16:26 UTC, BrandonPacewic commented on fission/vite.config.ts
Same as other formatting changes comment.

2025-06-18 16:39 UTC, Dhruv-0-Arora commented on fission/src/systems/scene/SceneRenderer.ts
> +        // })
Removed the comments

2025-06-18 16:40 UTC, Dhruv-0-Arora commented on fission/.eslintrc.cjs
Ill revert the changes to .eslintrc.cjs and ill keep the changes for the readme and postcss config

2025-06-18 16:42 UTC, Dhruv-0-Arora commented on fission/tailwind.config.mjs
Reverted

2025-06-18 16:42 UTC, Dhruv-0-Arora commented on fission/vite.config.ts
Reverted

2025-06-18 18:40 UTC, BrandonPacewic requested changes
Small merge conflict.

2025-06-19 20:19 UTC, PepperLola reviewed
I think it looks good. We might want to eventually make the settings tabbed rather than opening new panels with buttons but that should happen after the UI refactor. I suggested a change for a typo but other than that I think it's ready to merge.

Do we want to limit the maximum values that someone can choose? I think the upper end of the texture size values is almost impossible to run at an acceptable frame rate (especially since most people will probably be using chromebooks), so would it make sense to limit options that would tank performance like that to ones that are actually feasible to run? Especially if the settings are persisted, because it would be hard to reset the values if it takes a minute to click each button.

2025-06-19 20:19 UTC, PepperLola commented on fission/src/systems/scene/SceneRenderer.ts
> +        // Adding the lighting uisng quality preferences
```suggestion
        // Adding the lighting using quality preferences
```

2025-06-19 22:39 UTC, Dhruv-0-Arora commented
> I think it looks good. We might want to eventually make the settings tabbed rather than opening new panels with buttons but that should happen after the UI refactor. I suggested a change for a typo but other than that I think it's ready to merge.
> 
> Do we want to limit the maximum values that someone can choose? I think the upper end of the texture size values is almost impossible to run at an acceptable frame rate (especially since most people will probably be using chromebooks), so would it make sense to limit options that would tank performance like that to ones that are actually feasible to run? Especially if the settings are persisted, because it would be hard to reset the values if it takes a minute to click each button.

@PepperLola 
Currently I have the max shadow map size set to the renderers maxTextureSize capability, so on slower computers it will automatically limit the user. We could also manually set the value.

![Screenshot 2025-06-19 at 3 39 01 PM](https://github.com/user-attachments/assets/a106f2be-e056-4ff3-b9d0-57aa36d8d1a5)

2025-06-20 16:53 UTC, BrandonPacewic approved these changes
I think it's time to move onto something else. I have a few remaining issues that I think we should address after the UI refactor:

1. I agree that this should probably be a tab within the setting panel itself, rather than opening a new panel.
2. I think that we should consider splitting up the settings into collections (maybe a drop down) of basic and advanced.
3. I'm not that big of a fan of how we currently handle settings that need a refresh to take effect, again something that will be easier to handle (or at least implement) post UI refactor.
4. I think removing the presets all together is not what we want the final version of this to look like. I'm adding this as an additional task blocked by AARD-1781.

Since all my problems are essentially just UI nitpicks and the functionality is here I think its appropriate to make these changes after we finish the UI refactor.

2025-06-20 21:48 UTC, PepperLola approved these changes
I think it looks good except for the max texture size issues. In my experience it isn't properly limited and setting it too high can cause the app to become entirely unusable. I'm willing to leave that until later though, but I do think it should be addressed at some point.

2025-06-20 21:50 UTC, BrandonPacewic commented
> I think it looks good except for the max texture size issues. In my experience it isn't properly limited and setting it too high can cause the app to become entirely unusable. I'm willing to leave that until later though, but I do think it should be addressed at some point.

Noted.

2025-06-20 21:53 UTC, merged