SyntheSimJava Documentation
Autodesk/synthesis pull request #1094
Opened 2024-08-13 22:55 UTC by azaleacolburn

### Description
Documentation for SyntheSimJava

No JIRA Issue

2024-08-20 16:32 UTC, BrandonPacewic approved these changes
⭐

2024-08-20 18:29 UTC, a-crowell approved these changes
LGTM!

2024-08-20 20:20 UTC, PepperLola commented on simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/revrobotics/CANSparkMax.java
> +     *
```suggestion
```

2024-08-20 20:21 UTC, PepperLola commented on simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/revrobotics/SparkAbsoluteEncoder.java
> +     * Returns: The average sampling depth
```suggestion
     * @return The average sampling depth
```

2024-08-20 20:22 UTC, PepperLola requested changes
I think it's worth changing the Java comments to use the Javadoc format so people who use the library can get intellisense native to their editor.

2024-08-21 17:18 UTC, HunterBarclay commented on simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/ctre/TalonFX.java
> +    /// I think we're getting percentOutput and torque mixed up
Still keeping this comment here?

2024-08-21 17:19 UTC, azaleacolburn commented on simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/ctre/TalonFX.java
> +    /// I think we're getting percentOutput and torque mixed up
oh ya thanks

2024-08-21 17:19 UTC, azaleacolburn commented on simulation/SyntheSimJava/src/main/java/com/autodesk/synthesis/ctre/TalonFX.java
> +    /// I think we're getting percentOutput and torque mixed up
```suggestion
```

2024-08-22 00:58 UTC, PepperLola approved these changes
I think it looks good now. I made some changes that you're free to revert if you want.

2024-08-22 16:21 UTC, BrandonPacewic reviewed
> I think it looks good now. I made some changes that you're free to revert if you want.
> 
> Edit: It looks like I introduced a merge conflict by adding a class comment. I think that should stay there but maybe the import should be removed if it was added in this PR?

The merge conflict was just due to this branch not being up to date with dev where that commented import was already removed.

Looks good to go as long as @azaleacolburn is ok with the pushed changes ✅

2024-08-22 19:47 UTC, merged