Add Updater
Autodesk/synthesis pull request #656
Opened 2020-09-09 23:53 UTC by nicolasespinoza

### Add Updater
- Added and slightly refactored Updater from previous Unity Synthesis ([1](https://github.com/Autodesk/synthesis/blob/master/engine/Assets/Scripts/Engine/Utilities/VersionManager.cs)) ([2](https://github.com/Autodesk/synthesis/blob/master/engine/Assets/Scripts/Engine/Utilities/UnityHandler.cs))
- Added Dialog UI for notification which opens respective update version URL

![Annotation 2020-09-09 164547](https://user-images.githubusercontent.com/31714622/92665877-85283680-f2bc-11ea-817b-7019667d695b.png)

**How to test**
One way to test the functionality updater is to invert the if statement [here](https://github.com/Autodesk/synthesis/blob/54c8d70f05bbd3e64395736b4897c1f262e90a2d/modules/SynthesisCore/UI/Ui.cs#L85), which will display the dialog. Please note the information there will be invalid though because of the inverted if statement. This will not happen in production.

Closes #534

2020-09-10 03:05 UTC, matthew17754 requested changes
We should also add a reference to display the installed version number somewhere else in the GUI, such as the bottom left of the Settings or Help menus. Also some small suggestions below.

2020-09-10 03:05 UTC, matthew17754 commented on modules/SynthesisCore/Utilities/Updater.cs
> +                Logger.Log("[Updater] Connection to version checker failed", LogLevel.Warning);
`Connection to update servers failed` would be more fitting

2020-09-21 21:13 UTC, KiraCorbett approved these changes
Looks good. Thanks for adding the versioning number too.

2020-09-21 21:30 UTC, matthew17754 approved these changes
Looks good. 👍

2020-09-21 21:31 UTC, merged