1266 redo toolbar
Autodesk/synthesis pull request #718
Opened 2021-06-24 22:00 UTC by victorxheng

The new Tab-Holder prefab uses a horizontal layout group and content size fitter to format the tabs and can be modified easily in the future. Each tab prefab is a button updated with a Text Mesh Pro text. Scaling was also fixed.

The new Add-Category prefab is built off what was previously there but this time uses horizontal layout groups and content size fitters to format the button icons and labels, which are now updated with Text Mesh Pro text. The scaling was also fixed.

AARD-1266:
[Redo Toolbar Tabs](https://jira.autodesk.com/browse/AARD-1266)

2021-06-25 23:44 UTC, matthew17754 approved these changes
Looks ok, other than the merge conflicts

2021-06-28 18:58 UTC, victorxheng commented
I made toolbar switching into a prefab and UnityResyncer unit test.

[Create UI Toolbar](https://jira.autodesk.com/browse/AARD-1262)
[Redo Toolbar Tabs](https://jira.autodesk.com/browse/AARD-1266)
[Unity Resyncer Testing](https://jira.autodesk.com/browse/AARD-1264)

2021-06-28 22:22 UTC, KyroVibe requested changes
Add a new gameobject with the sole intention of containing the UnityResyncerComponent

2021-06-28 22:22 UTC, KyroVibe commented on engine/Assets/Scripts/SampleTest.cs
> +public class SampleTest : MonoBehaviour
Remove this Test script as it was implemented as a unit test somewhere else

2021-06-29 07:36 UTC, KyroVibe approved these changes
Made some final touches with the gitignore and some files you accidently deleted from the git history. All good to go

2021-06-29 07:37 UTC, merged