Updated hierarchy view with correct displays
Autodesk/synthesis pull request #719
Opened 2021-06-24 23:23 UTC by khuntetad

The new hierarchy clearly displays the folders and subitems with padding. In order to fix this, the mask containing the text was expanded, and a content size fitter was implemented in order to fix the scaling. A before and after of the hierarchy view can be found below.

Before:
![Screenshot (1)](https://user-images.githubusercontent.com/63430428/123343931-a4204e00-d507-11eb-88f5-5f8cce12ec3d.png)

After:
![Screenshot (2)](https://user-images.githubusercontent.com/63430428/123344000-c31ee000-d507-11eb-8822-cde1f90481bb.png)

AARD-1263
[Add Hierarchy view back to Scene](https://jira.autodesk.com/browse/AARD-1263)

2021-06-27 02:07 UTC, matthew17754 approved these changes

2021-06-28 22:38 UTC, KyroVibe requested changes
Move the hierarchy to be closer to the side of the screen and move it a bit down to make it look a bit nicer

2021-06-28 22:38 UTC, KyroVibe commented on engine/Assets/Scripts/UI/Hierarchy/Hierarchy.cs
> +            rootFolder.Init("Scene ajsdf;lajsd;lfajs", null);
Rename all the items back to their original names

2021-06-28 22:38 UTC, KyroVibe commented on engine/Assets/Scripts/UI/Hierarchy/Hierarchy.cs
>              robots.CreateItem("997 Spartan Robotics");
Get rid of the ErrorCode and Spartan Robotics example items

2021-06-28 22:38 UTC, KyroVibe commented on engine/Assets/Scripts/HierarchyTest.cs
> +public class HierarchyTest : MonoBehaviour
Remove this test script. It doesn't work

2021-06-29 23:02 UTC, KyroVibe approved these changes
Looks good, nice work pushing through the insanity we call Unity

2021-06-29 23:03 UTC, merged