Moved Importer and Translator
Autodesk/synthesis pull request #723
Opened 2021-06-30 18:05 UTC by KyroVibe

Moved the importer from the Importer sln to the Engine
Moved the translator into the Api sln
Moved Aardvark libraries accordingly
Some small changes to serialization of translated files
Deleted the Importer sln
I accidentally commited the new camera controller so I think imma just leave it in

2021-06-30 21:47 UTC, KyroVibe commented
Branch finally passes CI

2021-06-30 22:07 UTC, matthew17754 approved these changes
No Kermit. Looks good.

2021-07-01 17:52 UTC, victorxheng requested changes

2021-07-01 17:52 UTC, victorxheng commented on engine/Assets/Scripts/Camera/CameraController.cs
> +        if (Input.GetKeyDown(KeyCode.Mouse0)) {
Ignore input when using UI

2021-07-01 23:33 UTC, victorxheng approved these changes

2021-07-01 23:33 UTC, merged