Proto api integration
Autodesk/synthesis pull request #732
Opened 2021-07-23 23:23 UTC by Aaron7317

Created ControllableState and RobotManager classes. ControllableState stores a signal layout and holds values for those signals. RobotManager stores a Dictionary of ControllableStates and has a ConcurrentQueue for updating them. I changed UpdateMessage to UpdateSignals and changed it to match the format of the mirabuf Signals. I also cleaned up the TcpServer a bit. It now doesn't need locks and its still thread safe (I think). It now has a SetTargetQueue method which sets the queue it will send the updates it recieves to. I made a couple of tests as well but commented out one of them because it uses the TcpServer.

2021-07-24 00:53 UTC, KyroVibe requested changes

2021-07-24 00:53 UTC, KyroVibe commented on api/Api/Proto/Assembly.cs
> +// <auto-generated>
Add all the generated protobuf files to the gitignore

2021-07-24 00:53 UTC, KyroVibe commented on api/Api/Utilities/ControllableState.cs
> +        private Signals? _currentSignalLayout;
If you could add some documentation to the controllable state that would be great. Just like a sentence or two of what it's supposed to do at the top

2021-07-25 22:04 UTC, Aaron7317 commented
Made requested changes and changed the Update method in ControllableState to make sure each Signal being updated is part of the current layout

2021-07-26 18:18 UTC, NickBurrell approved these changes

2021-07-26 18:19 UTC, KyroVibe approved these changes

2021-07-26 18:19 UTC, NickBurrell commented
Forgot to add a comment to my previous message, but everything looks good. The unit tests are still broken, for somewhat unknown reasons, but this is an issue that we can investigate at a later time (as we planned to).

2021-07-26 18:32 UTC, matthew17754 requested changes
For some reason CI checks are stalling and there's still protobuf generated C# files present.

2021-07-26 23:37 UTC, matthew17754 requested changes

2021-07-26 23:37 UTC, matthew17754 commented on api/Api/Proto/Joint.cs
> +// </auto-generated>
`Joint.cs` should be removed

2021-07-27 04:40 UTC, KyroVibe approved these changes

2021-07-27 05:43 UTC, KyroVibe commented
I added an init script so instead of manually setting up the project, init will initialize the mirabuf submodule and generate all the proto files. Matt if you want you could try doing that for your CI

2021-07-27 06:48 UTC, matthew17754 approved these changes

2021-07-27 06:49 UTC, merged