Local Multiplayer Implementation
Autodesk/synthesis pull request #734
Opened 2021-07-26 19:19 UTC by khuntetad

Created a Local Multiplayer panel which allows the user to spawn in robots and also switch between different robot cameras. In the example below, you can see the camera at different positions when different multiplayer buttons are selected. In order to access the Local Multiplayer feature, hit the Multiplayer tab and then the controller icon.

![Screenshot (5)](https://user-images.githubusercontent.com/63430428/127045398-05ddc947-135d-4127-9e0b-b2e2846feb67.png)
![Screenshot (6)](https://user-images.githubusercontent.com/63430428/127045419-5c2a009e-299b-4783-aa14-d1a5ea32ee10.png)
AARD-1322
[Local Multiplayer](https://jira.autodesk.com/browse/AARD-1322)

2021-07-26 20:46 UTC, victorxheng approved these changes

2021-07-29 01:06 UTC, NickBurrell requested changes
Functionality wise it works, however, I do have some issues with the UI panel itself. The buttons aren't labeled, aside from one, who's label is merely "label". Its a bit hard to discern which button does which thing. 

If you could pick icons for the buttons that are more suitable, and label the buttons on the panel appropriately, this would be best.

2021-07-29 01:26 UTC, KyroVibe commented
@khuntetad As an alternative to Nicks comment, could you just move the multiplayer button to the main tab with the other buttons we are using rn. Also add a label under the button saying "local multiplayer" or something. Btw merge conflicts now

2021-07-29 19:03 UTC, KyroVibe approved these changes

2021-07-29 19:03 UTC, NickBurrell approved these changes

2021-07-29 19:04 UTC, merged