Updater and Touch ups
Autodesk/synthesis pull request #792
Opened 2022-08-15 04:32 UTC by KyroVibe

# Tasks
### Updater Modal
- [x] Created new updater panel that is prompted to the user when a new latest version has been detected
- [x] Changed new current version to be 5.0.0 instead of 4.3.3

### Main Menu
- [x] Changed background to be inverted and blurred Autodesk material
- [x] Added title and logo to main menu

### HUD
- [x] Added new icons to the options in the HUD. Will need to be adjusted when [Settings](https://github.com/Autodesk/synthesis/pull/788) is finished

# Match Mode
I'm going to vote we push match mode out to either release [5.1.0](https://jira.autodesk.com/projects/AARD/versions/113680) or potentially even just [5.0.1](https://jira.autodesk.com/projects/AARD/versions/114092). There are a ton of weird corner cases that users will try very quickly that it isn't ready to handle, plus the UI manager needs a quick overhaul as when creating the new UI system, the manager took a backseat. The pre-requisite tasks are going to be addressed during the build-up to these upcoming releases and match mode will follow suit.

2022-08-15 17:38 UTC, NickBurrell requested changes
Tested, fixes made. Everything looks good, approved.

2022-08-15 17:44 UTC, NickBurrell approved these changes

2022-08-15 22:37 UTC, MattMoradi requested changes

2022-08-15 22:37 UTC, MattMoradi commented on VersionManager.json
> +  "Version": "5.0.0",
This file should not be changed until after the release has been published

2022-08-21 01:35 UTC, NickBurrell approved these changes

2022-08-24 03:26 UTC, MattMoradi approved these changes

2022-08-24 03:26 UTC, merged