Match state machine and robot placement
Autodesk/synthesis pull request #859
Opened 2023-06-28 21:44 UTC by LucaHaverty

### Description
A state machine to control match mode. Contains states for things like configuring the match and auto. Each state has a start, update, and end function that are called automatically by MatchStateMachine.cs. The state machine will allow the user to configure, enter, play, and exit a match.

In addition to the state machine, there is a new robot placement system that is used when positioning robots before a match. This allows the user to select a location with their mouse and the robot will automatically be positioned slightly above the field.

### Objectives (mostly different states to create basic functionality for)
- [ ] State machine framework
- [ ] Add match mode to main menu instead of "coming soon"
- [x] Match config menu (robot and field selection, other settings)
- [x] Spawn all robots without gizmos
- [x] Robot placement state with new placement functionality
- [ ] Auto and teleop state
- [ ] After match analysis state

### Testing Done
- Robot placement on different fields with different robots

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1493)

2023-06-28 23:49 UTC, PepperLola requested changes
I think maybe the `MatchResultsModal` accept button should close the panel and set the match state to `None`? Also rename `MatachResults` to `MatchResults`.

2023-06-29 16:22 UTC, BrandonPacewic requested changes
Mainly just related to cleanups.

2023-06-29 16:22 UTC, BrandonPacewic commented on engine/Assets/Scripts/Gizmos/GizmoManager.cs
> +            Debug.Log("spawn gizmo");
`Debug.Log` still needed?

2023-06-29 16:22 UTC, BrandonPacewic commented on engine/Assets/Scripts/Modes/MatchMode.cs
> +        });*/
Can this code block be removed?

2023-06-29 16:22 UTC, BrandonPacewic commented on engine/Assets/Scripts/UI/Dynamic/Modals/Spawning/MatchModeModal.cs
> +            .AddOnValueChangedEvent((d, i, data) => _allianceColor = i).ApplyTemplate(VerticalLayout);*/
Can this code block be removed?

2023-06-29 16:22 UTC, BrandonPacewic commented on engine/Assets/Scripts/UI/Dynamic/Modals/Spawning/MatchModeModal.cs
> +        Scoring.ResetScore();*/
Can this code block be removed?

2023-06-29 16:22 UTC, BrandonPacewic commented on engine/Assets/Scripts/UI/Dynamic/Panels/Configuring/StartMatchModePanel.cs
> +            //PanelImage.RootGameObject.SetActive(false);
Can this line be removed?

2023-06-29 16:22 UTC, BrandonPacewic commented on engine/Assets/Scripts/UI/Dynamic/Panels/Configuring/StartMatchModePanel.cs
> +            //GizmoManager.SpawnGizmo<RobotSimObject>(RobotSimObject.GetCurrentlyPossessedRobot());
Can this line be removed?

2023-06-29 16:22 UTC, BrandonPacewic commented on engine/Assets/Scripts/UI/Dynamic/Panels/SpawnLocationPanel.cs
> +       }*/
Can this code block be removed?

2023-06-29 16:22 UTC, BrandonPacewic commented on engine/Assets/Scripts/Modes/MatchStateMachine.cs
> +                MatchStateMachine.Instance.SetState(StateName.MatchResults);
Still needed?

2023-06-29 16:54 UTC, BrandonPacewic commented on engine/Assets/Scripts/Modes/MatchStateMachine.cs
> +                MatchStateMachine.Instance.SetState(StateName.MatchResults);
👍

2023-06-29 20:58 UTC, PepperLola requested changes
~~I'm not sure if it's an issue on my end, but I wasn't able to rotate the robot without snapping by holding shift. With snapping, it would rotate normally, but when holding shift it wouldn't rotate at all.~~

Nevermind, maybe change snapping from a toggle to a hold control?

2023-06-29 21:08 UTC, BrandonPacewic commented
> Nevermind, maybe change snapping from a toggle to a hold control?

Is it a toggle right now? I agree it should be a hold.

2023-06-29 21:13 UTC, Markytt approved these changes

2023-06-29 21:51 UTC, PepperLola approved these changes
Everything looks good now!

2023-06-30 02:24 UTC, merged