Color Manager & Themes
Autodesk/synthesis pull request #882
Opened 2023-07-07 20:23 UTC by LucaHaverty

### Description
Refactors the current color manager to have better names and support for multiple themes. A new theme system will allow users to switch between color themes and create their own or modify existing ones through the appdata folder. The themes will affect UI as well as the skybox and floor color. 

### Objectives
- [x] Create a new color manager system
- [x] Add support for themes
- [x] Set up an event system to update everything that uses colors when the theme is changed
- [ ] Convert all existing color code to the improved color manager
- [ ] Add theme switching to the settings modal
- [ ] Rename colors so they make more sense and add things such as floor and skybox to the color manager

### Testing Done
-

[JIRA Issue (Color Manager)](https://jira.autodesk.com/browse/AARD-1556)
[JIRA Issue (Themes)](https://jira.autodesk.com/browse/AARD-1557)

2023-07-11 16:05 UTC, BrandonPacewic requested changes
I had some problems when trying to load and create a new theme.

Unity Error:

```
IndexOutOfRangeException: Index was outside the bounds of the array.
UI.Dynamic.Modals.Configuring.ThemeEditor.EditThemeModal.SetThemePref () (at Assets/Scripts/UI/Dynamic/Modals/Configuring/ThemeEditor/EditThemeModal.cs:246)
UI.Dynamic.Modals.Configuring.ThemeEditor.EditThemeModal.SelectTheme (System.Int32 index) (at Assets/Scripts/UI/Dynamic/Modals/Configuring/ThemeEditor/EditThemeModal.cs:222)
UI.Dynamic.Modals.Configuring.ThemeEditor.EditThemeModal.Create () (at Assets/Scripts/UI/Dynamic/Modals/Configuring/ThemeEditor/EditThemeModal.cs:63)
Synthesis.UI.Dynamic.DynamicUIManager.CreateModal[T] (System.Object[] args) (at Assets/Scripts/UI/Dynamic/DynamicUIManager.cs:76)
```

And my `Select a Theme` menu looked like this:

<img width="545" alt="Screenshot 2023-07-11 at 9 04 08 AM" src="https://github.com/Autodesk/synthesis/assets/92102436/af8971a0-b538-46b9-b9f2-9944f524efe9">

It looks like it's having problems loading the preset themes.

2023-07-11 17:47 UTC, LucaHaverty commented
> I had some problems when trying to load and create a new theme.
> 
> Unity Error:
> 
> ```
> IndexOutOfRangeException: Index was outside the bounds of the array.
> UI.Dynamic.Modals.Configuring.ThemeEditor.EditThemeModal.SetThemePref () (at Assets/Scripts/UI/Dynamic/Modals/Configuring/ThemeEditor/EditThemeModal.cs:246)
> UI.Dynamic.Modals.Configuring.ThemeEditor.EditThemeModal.SelectTheme (System.Int32 index) (at Assets/Scripts/UI/Dynamic/Modals/Configuring/ThemeEditor/EditThemeModal.cs:222)
> UI.Dynamic.Modals.Configuring.ThemeEditor.EditThemeModal.Create () (at Assets/Scripts/UI/Dynamic/Modals/Configuring/ThemeEditor/EditThemeModal.cs:63)
> Synthesis.UI.Dynamic.DynamicUIManager.CreateModal[T] (System.Object[] args) (at Assets/Scripts/UI/Dynamic/DynamicUIManager.cs:76)
> ```
> 
> And my `Select a Theme` menu looked like this:
> 
> <img alt="Screenshot 2023-07-11 at 9 04 08 AM" width="545" src="https://user-images.githubusercontent.com/92102436/252723946-af8971a0-b538-46b9-b9f2-9944f524efe9.png">
> It looks like it's having problems loading the preset themes.

If anyone else is still having issues with a blank theme, go into your synthesis appdata folder and delete any themes without a name or named Default.

2023-07-11 17:57 UTC, BrandonPacewic reviewed
Could we have a button that will reset our custom saved themes?

2023-07-11 18:04 UTC, LucaHaverty commented
> Could we have a button that will reset our custom saved themes?

Do you mean reset to the defaults or reset just the most recent changes?

2023-07-11 18:08 UTC, BrandonPacewic commented
> > Could we have a button that will reset our custom saved themes?
> 
> Do you mean reset to the defaults or reset just the most recent changes?

I mean reset all custom saved themes. So basically just remove all the files in the themes folder on your computer.

2023-07-11 21:06 UTC, Markytt requested changes
Could you add a cancel button to the button left corner of the theme editor panel, right now the only way to close it is by clicking the save button. 
![Screenshot 2023-07-11 140411](https://github.com/Autodesk/synthesis/assets/111198108/305f1852-522d-4f16-8769-82eacea2b783)

2023-07-12 16:35 UTC, BrandonPacewic reviewed
It looks like some / all of the analytics updates are in here. Was that on purpose?

2023-07-12 21:02 UTC, KyroVibe requested changes
Couple things I've noticed:

1. The three dashes at the top of the MainHUD doesn't update to a new color.
2. The version text doesn't update either.
3. When the grid lines are set to black, the grid is actually grey.
4. If the themes folder doesn't exist, getting existing themes breaks.

Also I know it's kinda late to ask this, but could we switch the color selection to HSV instead of RGB?

2023-07-13 16:18 UTC, LucaHaverty commented
@KyroVibe The three dashes on the main HUD update for me. They are set to the icon color.

2023-07-13 16:20 UTC, LucaHaverty commented
> It looks like some / all of the analytics updates are in here. Was that on purpose?

Yeah I accidentally made this branch off of analytics instead of dev. Hunter said it's fine but we have to merge analytics before this.

2023-07-13 18:01 UTC, BrandonPacewic reviewed
Everytime I click on a panel it stays highlighted.

<img width="745" alt="Screenshot 2023-07-13 at 11 00 51 AM" src="https://github.com/Autodesk/synthesis/assets/92102436/c83568c9-5150-4399-a697-b6ae25c9fc8e">

2023-07-13 20:58 UTC, BrandonPacewic reviewed
~~When I click on preview everything gets highlighted.~~

<img width="756" alt="Screenshot 2023-07-13 at 1 58 10 PM" src="https://github.com/Autodesk/synthesis/assets/92102436/13897a20-579f-425a-99ff-cc4d681c5b2b">

2023-07-13 21:58 UTC, Markytt commented
> I like the UI and it seems to work pretty well! I did find a couple issues though
> 
> * If you try to edit a theme from the main menu after exiting from the main scene, it will throw an exception trying to create a theme, cancel the editor, or accept, because TopBar has been destroyed. The Create Theme modal will also not close the theme editor one.
> * If you create a theme in the main menu and then try to enter the main scene, it will throw a KeyNotFoundException because the "escape_menu" key isn't in controls (although I'm not sure that's specifically an issue with this PR)
> 
> Along with this, maybe an "Apply" button would be nice so you can preview changes without having to save them, and so that you can adjust the settings easily to find one you like instead of having to exit and re-enter every time you want to update the colors.

Just going to the main menu and re-entering practice mode will also cause the KeyNotFoundException 

![Screenshot 2023-07-13 142015](https://github.com/Autodesk/synthesis/assets/111198108/8ee46a53-e54d-4028-b697-10debd39a5de)
![Screenshot 2023-07-13 142030](https://github.com/Autodesk/synthesis/assets/111198108/04ca66cf-803c-4573-91ed-9732dbf907a4)
![Screenshot 2023-07-13 142053](https://github.com/Autodesk/synthesis/assets/111198108/2333b701-3d5d-4064-bfc0-c5b33ef2b8e4)

2023-07-13 22:02 UTC, LucaHaverty commented
Yeah it happens whenever you enter practice mode

2023-07-13 23:33 UTC, LucaHaverty commented
@BrandonPacewic I am getting a format validation error even though I ran the formatter. It says the error is on line 35 of ColorManager.cs.

2023-07-13 23:52 UTC, BrandonPacewic commented
@LucaHaverty Fixed it, is this pr ready for review?

2023-07-14 00:00 UTC, LucaHaverty commented
> @LucaHaverty Fixed it, is this pr ready for review?

@BrandonPacewic Yes

2023-07-14 00:30 UTC, BrandonPacewic commented on engine/Assets/Scripts/Utilities/ColorManager/ColorManager.cs
> +                             "Synthesis" + Path.AltDirectorySeparatorChar + "Themes";
To make this more readable I think we should save the separation character to a variable.

```cs
char altSep = Path.AltDirectorySeparatorChar;
```

Other than that looks good.

2023-07-14 01:06 UTC, KyroVibe approved these changes
Added a quick shader fix previously not seen due to a fixed grid line color. Nice work

2023-07-14 16:26 UTC, BrandonPacewic approved these changes
Nice work, very impressed that you got this done so quickly!

2023-07-14 16:36 UTC, Markytt reviewed
Changing/editing the theme editor in the main menu still causes a MissingReferenceException. Other than that though, all of the other bugs appear to have been fixed. 
![Screenshot 2023-07-14 093321](https://github.com/Autodesk/synthesis/assets/111198108/1ad9bf88-ddb3-4201-92ba-cbf703b5d332)

2023-07-14 16:55 UTC, PepperLola requested changes
Sorry Luca, I know you want to be done with this, but do you think you could make it so that when you delete a theme, it resets all of the values back to default? I created a theme and changed a color, then deleted the theme and the colors stayed visible even though the default theme was selected. I created a new theme and these colors were automatically applied and the default one was reset back to normal. I also think that when you create a new theme, it should automatically have the default theme colors regardless of which theme you have selected. It seems like this is an issue with the preview stuff but I'm not sure.

2023-07-14 17:09 UTC, LucaHaverty commented
> Sorry Luca, I know you want to be done with this, but do you think you could make it so that when you delete a theme, it resets all of the values back to default? I created a theme and changed a color, then deleted the theme and the colors stayed visible even though the default theme was selected. I created a new theme and these colors were automatically applied and the default one was reset back to normal. I also think that when you create a new theme, it should automatically have the default theme colors regardless of which theme you have selected. It seems like this is an issue with the preview stuff but I'm not sure.

@PepperLola I can't seem to recreate that issue. Did you use "delete selected" or "delete all"? And did you save the theme before deleting it? And in the main menu or in practice mode?

2023-07-14 17:12 UTC, PepperLola commented
> > Sorry Luca, I know you want to be done with this, but do you think you could make it so that when you delete a theme, it resets all of the values back to default? I created a theme and changed a color, then deleted the theme and the colors stayed visible even though the default theme was selected. I created a new theme and these colors were automatically applied and the default one was reset back to normal. I also think that when you create a new theme, it should automatically have the default theme colors regardless of which theme you have selected. It seems like this is an issue with the preview stuff but I'm not sure.
> 
> @PepperLola I can't seem to recreate that issue. Did you use "delete selected" or "delete all"? And did you save the theme before deleting it? And in the main menu or in practice mode?

This was on the main menu if that affects anything. What I did was:
1. Create new theme
2. Change primary color
3. Click preview
4. Delete selected
5. Create new theme
6. Preview/save theme
I didn't test it very extensively so it's possible that it's only the preview colors that are being carried over, but regardless I think they should automatically reset to the defaults when you create a new theme.

2023-07-14 17:37 UTC, PepperLola approved these changes
Looks good! The colors aren't carried over when deleting or creating new themes and I'm able to exit to the main menu and still change themes. ~~For some reason when I pulled, the AddRobotModal wasn't imported in ServerTestMode. I'm still going to approve the PR, but I would check if that's an issue on your end before merging.~~ Nevermind, you just fixed it.

2023-07-14 18:20 UTC, Markytt approved these changes
Looks like there are no more issue. Good job.

2023-07-14 18:40 UTC, BrandonPacewic commented
@LucaHaverty All done making changes?

2023-07-14 20:50 UTC, merged