Mix & Match Robot Creation
Autodesk/synthesis pull request #887
Opened 2023-07-12 17:11 UTC by LucaHaverty

### Description
Create a robot in Synthesis out of smaller parts. Eventually, we can add several pre made parts, but the user will also be able to make their own parts. This is still TBD, but mix and match mode may allow for assemblies to be made out of smaller parts, then used as one component on a robot.

This feature may take a long time as I plan to pause for sprint 3 to work on UI.

### Objectives
- [x] System for different object to be combined at "snap points"
- [ ] Robot creation panel
- [ ] Part creation panel
- [ ] Mix and match sim object
- [ ] Part assemblies?

### Testing Done
-

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1566)

2023-08-08 17:48 UTC, KyroVibe requested changes

2023-08-08 17:48 UTC, KyroVibe commented on api/Api/Controller/ControllableState.cs
> +		public ControllableState(Signals[] allSignals) {
Switch to `params Signals[] allSignals` so it can still take single Signals

2023-08-12 01:56 UTC, a-crowell requested changes
Wow this is so cool! Everything for creating the parts and playing around with the robot worked great!


*Function Ideas:*

Is there a way to move the part editor in the scene, especially when there's a field loaded? The part can get hidden when there's something in the center of the field. On a similar note, having the physics freeze would help when a robot's in the way.

Can users choose which connection points they want to attach? When you have multiple it just seems to pick the first one.

Do we want any updating? Like when you edit the part, it'll adjust robots that use it or when you edit a robot, it'll adjust any on the field. I'm on the fence about it.

Is the elevator skewed for anyone else? Or is this not skewed and I simply misunderstood the arrows?
![0811MixMatch3](https://github.com/Autodesk/synthesis/assets/53123817/a7247c0d-a1ef-464e-bb4d-5a242c794de7)


*UX Ideas:*

UX looked pretty good as long as we have good tutorials for it. Maybe buttons guiding users to create if there are no robots/parts? When there are no robots in the spawn mix and match, we could replace the dropdown with a phrase "No robots built yet" and a "Build robot" button that takes users to the robot editor. Same with parts for the robot editor. It would be cool to bring the users back to the spawning modal when they're done, but I don't think it's necessary. If you do this to Mix and Match, later we should add it to regular robot/field spawning, no robots/fields downloaded leading to the Download Asset modal.

The Choose Your Part/Robot modals could be scrolling lists instead. Similar to Scoring Zones with the edit and delete buttons on each part and the add button at the bottom.

It would be nice to automatically select a part after users add it. Same thing with connection points in the part editor.


*Errors:*

In Robot Editor, the second time you press the parent button in the same session for one part.
![0811MixMatch](https://github.com/Autodesk/synthesis/assets/53123817/985d4de8-da9b-47cc-80ee-d434e1199efb)

While in Robot Editor (the panel selecting parts), opened mix and match modal and went through naming before canceling back out to robot editor. Haven't been able to recreate though.
![0811MixMatch2](https://github.com/Autodesk/synthesis/assets/53123817/67ae6ede-3bb2-42de-bcb6-810d17319daa)


Overall, awesome job! I really like the catches you have in there for stuff like naming bots the same name and deleting a part being used. Preventing a lot of breaks, but also lets the user know not to do that.

2023-08-15 20:38 UTC, KyroVibe reviewed
![image](https://github.com/Autodesk/synthesis/assets/20159878/7faeffc5-1848-49eb-adde-b8b414ef37d6)
Very awesome work. I think there a handful of little tweaks we should come up with to make it a little more user friendly surrounding the attachment nodes and what not, but that can wait until later. I'm going to continue testing it to make sure normal bots still work but its looking really good.

2023-08-16 18:31 UTC, BrandonPacewic reviewed
Are we moving this to sprint 4?

2023-08-17 16:51 UTC, Markytt requested changes
In the part editor, if you exit before saving the part, that will cause error messages to appear. 

![Screenshot 2023-08-17 094934](https://github.com/Autodesk/synthesis/assets/111198108/4fdef9f0-fc5c-49ae-84ed-0a293809d010)

![Screenshot 2023-08-17 094958](https://github.com/Autodesk/synthesis/assets/111198108/5f085d72-d605-4e7f-ab0c-c4e33c89b24a)

Other than that issue, everything else works great.

2023-08-17 16:57 UTC, a-crowell approved these changes
Looks great! Love the editor isolation.

List of bugs for later:

In robot editor, put an elevator on a swerve. With elevator still selected, add an arm and move your mouse over the bot. Then you get an elevator helicoptering away.
![0817MixMatchElevatorFly](https://github.com/Autodesk/synthesis/assets/53123817/630e6a38-3937-4101-a80a-a61beba92d9b)


Move an object another is connected/parented to. Less of a bug, and more of a cool feature to add, making it follow.
![0817MixMatchMoveParent](https://github.com/Autodesk/synthesis/assets/53123817/6e50a317-9cc4-465b-9e84-375c42de372c)

The more buggy part of the previous "bug." This was the same bot after then moving the arm onto the elevator
![0817MixMatchMoveParent2](https://github.com/Autodesk/synthesis/assets/53123817/0d183f02-9246-4457-8e2c-6ccf13e85ca7)

If you don't have your swerve on the bottom, likely due the swerve assuming it has the lowest wheels.
![0817MixMatchSwerve](https://github.com/Autodesk/synthesis/assets/53123817/e177c3ba-a084-4437-aedd-9c7241d0154a)
![0816MixMatch](https://github.com/Autodesk/synthesis/assets/53123817/576389bf-9a73-4e0d-b096-9f1495d8a208)

This is just a list for later of mostly user failure stuff--no crashes even! Great work!

2023-08-19 16:55 UTC, KyroVibe approved these changes
Can't wait for our users to cause absolute mayhem

2023-08-19 16:55 UTC, merged