Save Controls
Autodesk/synthesis pull request #907
Opened 2023-08-01 18:18 UTC by a-crowell

### Description
Make control schemes save between runs of Synthesis.

### Objectives
- [X] Save control schemes
- [ ] Make a Session Save vs Save button

### Testing Done
- Changing and checking if they save between runs: different drivebases and all of Team 2471 v7's joints

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1584)

2023-08-02 23:21 UTC, a-crowell commented
> Nice job! I'm not sure if this was intended, but when you have multiple different robots, they are both affected by the normal and session save.
> 
> The only other issue I found is that when you spawn two of the same robots, remove one, then edit controls you get this exception: ![image](https://user-images.githubusercontent.com/93229887/257871450-1c6fbdc0-6189-4aa5-851a-c0654198f2b3.png)

Fixed the multiple bots getting affected, but less sure about the fix for the error. Let me know if it shows up again.

2023-08-03 16:07 UTC, a-crowell commented
Don't pull right now, breaks other branches.

2023-08-03 18:50 UTC, a-crowell commented
> Don't pull right now, breaks other branches.

Wait until Save Controls Compatibility is in or uninstall and reinstall your mirabuf files when you're done to avoid errors when you switch branches.

2023-08-04 16:36 UTC, Markytt requested changes
Everything is working well, I didn't find any new bugs. Right now though, there is no way to close the controls panel without saving or doing a sessions save, so it would be nice if a close or cancel button was added to the controls panel.

2023-08-07 19:55 UTC, KyroVibe requested changes
Save and Session saved worked for robot controls. There are couple of things that need to be fixed however.

2023-08-07 19:55 UTC, KyroVibe commented on engine/Assets/Scripts/Behaviors/SwerveDriveBehaviour.cs
> +        private string reset_field_forward = "Swerve Reset Forward";
You forgot to append the id to the strings like how you did in ArcadeDrive

2023-08-07 19:55 UTC, KyroVibe commented on engine/Assets/Scripts/Behaviors/TankDriveBehavior.cs
> +        private string right_reverse = "Tank Right-Reverse";
Same issue as in SwerveDrive

2023-08-07 19:55 UTC, KyroVibe commented on engine/Assets/Scripts/Behaviors/ArcadeDriveBehaviour.cs
> +            forward  = SimObjectId + FORWARD;
This needs to be `MiraLive.MiraAssembly.Info.GUID` so it saves for multiple iterations of the same bot

2023-08-11 22:50 UTC, Markytt reviewed
The controls sometimes aren't saving when you change robots, or when you exit and re-enter practice mode. Also when you stop the program and run it again, the controls get reset to what they originally were.

2023-08-12 18:36 UTC, a-crowell commented
> The controls sometimes aren't saving when you change robots, or when you exit and re-enter practice mode. Also when you stop the program and run it again, the controls get reset to what they originally were.

Are you clicking Save, not Session Save? If so, may I ask which robots/controls you're changing?

2023-08-14 21:16 UTC, LucaHaverty requested changes
I found a few issues:

- Global control changes persist even if you click session save
- If you edit a robot control, click session, then enter the control modal again and click save, the changes still reset if you stop and play unity
- If you modify a global control and save without a field or robot spawned, you get
![image](https://github.com/Autodesk/synthesis/assets/93229887/6ad1a2ee-a017-4bf4-a95b-bb127af66926)

- If I edit controls mean machine then save or session save, there is a bit lag spike (multiple seconds). I haven't seen this happen with dozer

Saving and session saving robot controls seems to work well, nice work!

2023-08-14 22:07 UTC, a-crowell commented
> I found a few issues:
> 
> * Global control changes persist even if you click session save
> * If you edit a robot control, click session, then enter the control modal again and click save, the changes still reset if you stop and play unity
> * If you modify a global control and save without a field or robot spawned, you get
>   ![image](https://user-images.githubusercontent.com/93229887/260573451-6ad1a2ee-a017-4bf4-a95b-bb127af66926.png)
> * If I edit controls mean machine then save or session save, there is a bit lag spike (multiple seconds). I haven't seen this happen with dozer
> 
> Saving and session saving robot controls seems to work well, nice work!

Will get to work on the global control issues and look into optimizing Mean Machine! I figured we wouldn't want controls edited from the last time users opened the panel to Save, just so you can Session Save vs Save specific controls. What do y'all prefer? For now, I'll highlight the edited controls to make that clearer. Do y'all think something would be useful on the buttons themselves? Like "Save (2)" for 2 controls changed?

2023-08-15 15:38 UTC, LucaHaverty commented
> > I found a few issues:
> > 
> > * Global control changes persist even if you click session save
> > * If you edit a robot control, click session, then enter the control modal again and click save, the changes still reset if you stop and play unity
> > * If you modify a global control and save without a field or robot spawned, you get
> >   ![image](https://user-images.githubusercontent.com/93229887/260573451-6ad1a2ee-a017-4bf4-a95b-bb127af66926.png)
> > * If I edit controls mean machine then save or session save, there is a bit lag spike (multiple seconds). I haven't seen this happen with dozer
> > 
> > Saving and session saving robot controls seems to work well, nice work!
> 
> Will get to work on the global control issues and look into optimizing Mean Machine! I figured we wouldn't want controls edited from the last time users opened the panel to Save, just so you can Session Save vs Save specific controls. What do y'all prefer? For now, I'll highlight the edited controls to make that clearer. Do y'all think something would be useful on the buttons themselves? Like "Save (2)" for 2 controls changed?

Yeah I think that's a good idea

2023-08-15 19:29 UTC, KyroVibe requested changes
So very very close. When I session save, then spawn another one of the same bot, the controls reset to what they were before I session saved

2023-08-16 23:36 UTC, LucaHaverty approved these changes
I didn't find any issues. I like how changed controls are highlighted, great work!

2023-08-17 15:41 UTC, KyroVibe requested changes
Awesome work, add one more null check and you're done

2023-08-17 15:41 UTC, KyroVibe commented on engine/Assets/Scripts/Behaviors/ArcadeDriveBehaviour.cs
> +                            !(DynamicUIManager.ActiveModal as ChangeInputsModal).isSave)
```suggestion
                            (DynamicUIManager.ActiveModal as ChangeInputsModal)?.isSave ?? false)
```

2023-08-17 15:59 UTC, KyroVibe approved these changes
Great work, just added a quick null check

2023-08-17 16:00 UTC, KyroVibe approved these changes

2023-08-17 16:01 UTC, merged