Hotfix/pathing issue
Autodesk/synthesis pull request #943
Opened 2023-09-26 17:11 UTC by KyroVibe

### Description
- Changed file field in parts to store file name
- Added field to convert file name to absolute path
- Replaced usage of file name with new absolute path

2023-09-26 18:26 UTC, BrandonPacewic reviewed
Am I correct in saying that the robot builder parts will need to be created again and updated in the installer? Because I used the installer to get the parts in the first place it still will not work even with the current changes.

2023-09-26 19:02 UTC, KyroVibe commented
> Am I correct in saying that the robot builder parts will need to be created again and updated in the installer? Because I used the installer to get the parts in the first place it still will not work even with the current changes.

Yes. I fixed the ones on my machine and remaking them should result in the corrected path

2023-09-27 14:04 UTC, BrandonPacewic reviewed
Seems to work as far as I can tell. Although I'll admit I may not have tested this correctly as I am on my personal computer.

2023-09-27 16:26 UTC, KyroVibe commented on engine/Assets/Scripts/SimObjects/MixAndMatch/MixAndMatchSaveData.cs
> +        public static readonly string PART_MIRABUF_FOLDER_PATH =
It's (basically) a constant for the file path to the folder and its used externally from the class

2023-09-27 17:11 UTC, BrandonPacewic commented on engine/Assets/Scripts/SimObjects/MixAndMatch/MixAndMatchSaveData.cs
> +        public static readonly string PART_MIRABUF_FOLDER_PATH =
Gotcha.

2023-09-27 17:12 UTC, BrandonPacewic approved these changes
Seems ok. Send me a discord msg when you update the installer and have a new build. Want to test it again on my windows computer before we send it out.

2023-10-02 02:01 UTC, LucaHaverty requested changes
The fix works well when I create a new part, but it throws an error when loading an old part. Do you think you could add a check that fixes old parts in case people have them in appdata already when they install the update with this fix?

2023-10-03 06:52 UTC, KyroVibe commented
@LucaHaverty I added a check to see if the new path is found, if not, look for the old path, then if that's not found, throw an exception. We really need to add better error handling to everything mira

2023-10-05 04:44 UTC, LucaHaverty approved these changes
Works well, great work Hunter!

2023-10-05 22:25 UTC, merged