first attempt at windows assetpack download script
Autodesk/synthesis pull request #993
Opened 2024-06-25 16:23 UTC by Ewie21

### Description
Created assetpack download script for windows users using run-script-os

### Objectives
- [x] Assetpack download script attempt 1

### Testing Done
- [ ] Test download script on windows computer (Brandon)

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1715)

2024-06-25 18:09 UTC, BrandonPacewic commented on fission/package.json
> +        "assetpack:win32": "curl -o public/assetpack.zip https://synthesis.autodesk.com/Downloadables/assetpack.zip && tar -xf public/assetpack.zip"
```suggestion
        "assetpack:win32": "curl -o public/assetpack.zip https://synthesis.autodesk.com/Downloadables/assetpack.zip && tar -xf public/assetpack.zip -C public/"
```

Should be placed into the `public/` dir after unzip.

2024-06-25 18:10 UTC, BrandonPacewic requested changes
Also we should maintain the 2 space formatting for all `.json` files.

2024-06-25 20:46 UTC, BrandonPacewic approved these changes
Looks like there were still some files that were not up to date with the new formatting.

Download and unzip works on my Windows machine.

LGTM!

2024-06-26 21:10 UTC, HunterBarclay approved these changes
Works great on my windows machine
👍

2024-06-26 21:10 UTC, merged